apiVersion: v1
kind: Pod
metadata:
  name: my-webserver
  labels: 
    prod: myapp
spec:
  containers:
    - name: my-webserver-container
      image: nginx
      ports:
        - name: nginx-port
          containerPort: 80
