apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: my-pod
spec:
  containers:
  - name: my-pod
    image: nginx
    ports:80
      -name: nginx
       protocol: tcp
      containerPort:80   


